app/models.py
from . import db,login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model,UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(8))
    email = db.Column(db.String(255), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f'User {self.username}'

class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        return f'User {self.name}'


class Login:
    login = []

    def __init__(self, username, password):
        self.username = username
        self.password = password
        1


class Register:
    register = []

    def __init__(self, username, email, password, confirmpassword):
        self.username = username
        self.email = email
        self.password = password
        self.confirmpassword = confirmpassword


class Blog(db.Model):
    __tablename__ = 'blog'

    id = db.Column(db.Integer, primary_key=True)
    owner_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    description = db.Column(db.String(), index=True)
    category = db.Column(db.String(255), nullable=False)


def save_blog(self):
        Blog.all_blogs.append(self)


@classmethod
def clear_blogs(cls):
    Blog.all_blogs.clear()


@classmethod
def get_blogs(cls, title):

 response = []

app/models/blog.py
class Blog:

    def save_blog(self):
        Blog.all_blogss.append(self)


@classmethod
def clear_blogs(cls):
    Blog.all_blogs.clear()


@classmethod
def get_blogs(cls, title):

 response = []

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, RadioField, SelectField
from wtforms.validators import Required, Email, EqualTo
from ..models import *


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[Required()])
    submit = SubmitField('Submit')

class BlogForm(FlaskForm):

    title = StringField('Blog title',validators=[Required()])
    blog = TextAreaField('Blog', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)

from . import  views, errors

app/main/views.py
from flask import render_template, redirect, url_for, abort, request
from flask_login import login_required
from ..models import User,Blog
from .forms import UpdateProfile, BlogForm
from .. import db
from . import main
import requests
import json


@main.route('/')
def index():
    '''
    View root page function that returns the home page and its data
    '''

    blog = requests.get('http://quotes.stormconsultancy.co.uk/random.json').json()

    return render_template('index.html',blog = blog)


@main.route('/user/<name>')
def profile(name):
    user = User.query.filter_by(username=name).first()

    if user is None:
        abort(404)

    return render_template("Profile/profile.html", user=user, blogs=blogs)


@main.route('/user/<name>/update', methods=['GET', 'POST'])
@login_required
def update_profile(name):
    user = User.query.filter_by(username=name).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', name=user.username))

    return render_template('Profile/update.html', form=form)


@main.route('/user/<name>/update/pic', methods=['POST'])
@login_required
def update_pic(name):
    user = User.query.filter_by(username=name).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', name=name))


@main.route('/blog/new/', methods=['GET','POST'])
@login_required
def new_blog():
    '''
    Function that creates new blogs
    '''
    form = BlogForm()

    if form.validate_on_submit():
     Blog = form.body.data
     category = form.category.data
     new_blog = Blog(blog=Blog)
     new_blog.save_blog()
     return redirect(url_for('main.index'))

    return render_template('new_blog.html', new_blog_form = form)

app/templates/Profile/profile.html
{%extends 'base.html'%}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>
  {%block content%}
  <div class="container">
    <div class="row">
      <div class="wells">
        <div class="col-md-4">
          <h2> {{user.username| capitalize}} </h2>
          <br>

          {% if user.bio %}
          <p> {{user.bio}}</p>
          {%else%}
          <p> {{user.username| capitalize}} has no bio </p>
          {% endif %}
        </div>


        <div class="col-md-4" style='float:right;'>
          {% if user.profile_pic_path %}

          <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

          {%else%}
          <p>No profile picture</p>

          {% endif %}
          <br>

          {% if user == current_user %}
          <form action="{{url_for('main.update_pic',name=user.username)}}" method="post" enctype="multipart/form-data">

            <input type="file" name="photo" class="form-control" required>
            <input type="submit">
          </form>
          {% endif %}
        </div>
      </div>

    </div>
  </div>

  {% endblock %}

</body>

</html>

app/templates/Profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>
  {%block content%}
  <div class="container">
    <br>
    {{wtf.quick_form(form)}}
  </div>
  {%endblock%}
</body>

</html>

<SQLAlchemy engine=postgresql+psycopg2://moringa:***@localhost/blog>

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Styles block -->

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
<!-- Content block -->

{% block content %}
<!-- Content block -->
    <body>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Bloggers-app </title>
        {% endif %}
    </head>
    </body>
{% endblock%}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we couldn"t find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

<!-- Styles block -->

{% block styles%}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
  <link href="https://fonts.googleapis.com/css?family=Boogaloo" rel="stylesheet">
{% endblock %}

{% block content%}
<div class="Jumbotron">
<title align="center"> BLOGGERS-APP </title>
<div class="card" align="center">
    <h1> BLOGGERS-APP </h1>
    <p class="card-text">Blogging could be such a hard thing to learn but it's all in your head.</p>
    <a href="{{url_for('auth.login')}}" class="btn btn-primary"> Post a Blog</a>
</div>
<br>
<br>

<h2 align="center">{{blog.author}}</h2>
<h2 align="center">{{blog.quote}}</h2>
<hr>
<div class="row">
  <div class="col-md-6 col-lg-4">
    <div class="card" style="width: 18rem;">
    <img alt="Card image cap" class="card-img-top img-fluid" src="https://cdn2.wpbeginner.com/wp-content/uploads/2018/03/fashion-blog.jpg" height = "200" width = "300">
      <div class="card-block">
        <h4 class="card-title">FASHION BLOG</h4>

        <p class="card-text">Fashion blogs are one of the most popular types of blogs on the internet. It’s a big industry with a huge global audience. Fashion bloggers get invited to major events, receive special perks, merchandise, and even business deals by top fashion brands.</p>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-lg-4">
    <div class="card" style="width: 18rem;">
    <img alt="Card image cap" class="card-img-top img-fluid" src="https://cdn.wpbeginner.com/wp-content/uploads/2018/03/travel-blogs.jpg" height = "200" width = "300">
      <div class="card-block">
        <h4 class="card-title">TRAVEL BLOG</h4>

        <p class="card-text">Travel blogs are becoming more popular each day. Due to cheap air travel, people are traveling more than ever, and they are always looking for travel tips, advice, and destination guides.</p>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-lg-4">
    <div class="card" style="width: 18rem;">
    <img alt="Card image cap" class="card-img-top img-fluid" src="https://cdn4.wpbeginner.com/wp-content/uploads/2018/03/lifestyle-blogs.jpg"  height = "200" width = "300">
      <div class="card-block">
        <h4 class="card-title">LIFESTYLE BLOG</h4>

        <p class="card-text">Lifestyle blogs are the most popular type of blogs you can find online. They have a variety of readers, interested in topics ranging from culture, arts, local news, and politics. This gives the blogger a wide range of topics to cover, making it easier to plan their content strategy.</p>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-lg-4">
    <div class="card" style="width: 18rem;">
    <img alt="Card image cap" class="card-img-top img-fluid" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZTYW7L3aWf8aN81j5uEsVDStpA6EN4b-vZfwMPGZZtSjIggyMNQ"  height = "200" width = "300">
      <div class="card-block">
        <h4 class="card-title">FITNESS BLOG</h4>

        <p class="card-text">Fitness blogs has been a hot trend since they cover important topics like health and general fitness. People all over the world rely on the internet to seek advice on how to stay fit. It’s a great opportunity for fitness instructors to start a fitness blog and get clients online.</p>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-lg-4">
    <div class="card" style="width: 18rem;">
    <img alt="Card image cap" class="card-img-top img-fluid" src="https://cdn3.wpbeginner.com/wp-content/uploads/2018/03/food-blogs.jpg"  height = "200" width = "300">
      <div class="card-block">
        <h4 class="card-title">FOOD BLOG</h4>

        <p class="card-text">Food blogs are another popular blog type. It attracts a lot of readers who are interested in recipes, ingredients, healthy eating, fine dining, and other food related stories.</p>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-lg-4">
    <div class="card" style="width: 18rem;">
    <img alt="Card image cap" class="card-img-top img-fluid" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7WZaEP-tJWHwW_v5B1jgz_JLwgGGz5M6AWvYd-eFlI490VNEc" height = "200" width = "300">
      <div class="card-block">
        <h4 class="card-title">QUOTES..</h4>

        <p class="card-text">Quotation is the repetition of someone else's statement or thoughts. Quotation marks are punctuation marks used in text to indicate a quotation. Both of these words are sometimes abbreviated as "quote(s)".</p>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

app/templates/new_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-4">

            {{ wtf.quick_form(new_blog_form) }}
        </div>

    </div>

{% endblock %}